#   ------------------------------------------------------------
#   BASH_PROFILE
#   ------------------------------------------------------------

#   Change prompt
#   ------------------------------------------------------------
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\[\033[36m\]\u@\h:\[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

#   Set colors
#   ------------------------------------------------------------
export CLICOLOR=1
export LSCOLORS=agfxcxdxbxegedabagacad
export GREP_OPTIONS='--color=auto'

#   Source bashrc
#   ------------------------------------------------------------
source ~/.bashrc

