#   -----------------------------------------------------------
#   BASHRC
#   -----------------------------------------------------------

#   Include machine-specific shell commands
#   -----------------------------------------------------------
if [ -f ~/.shell_local ]; then
    source ~/.shell_local
fi

#   Set variables
#   -----------------------------------------------------------
# Some applications read the EDITOR variable to determine your favourite text
# editor
export EDITOR=/usr/bin/vim

#   Include unix shell functions
#   -----------------------------------------------------------
source ~/.functions

#   Include aliases
#   -----------------------------------------------------------
source ~/.aliases

